name: hello-world

on: push

job:
  hello-world-job:

    runs-on: ubuntu-latest

    steps:
      - name: check out repository code
        uses: actions/checkout@4
      - run: echo "$(cat hello_world.txt)"
